from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget , QLineEdit , QApplication , QPushButton

class Ui_Emp_reg(QWidget):
    def setupUi(self, Emp_reg):
        Emp_reg.setObjectName("Emp_reg")
        Emp_reg.resize(480, 488)
        self.layoutWidget = QWidget(parent=Emp_reg)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 390, 251, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Register = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.Register.setObjectName("Register")
        self.horizontalLayout.addWidget(self.Register)
        self.Cancel = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout.addWidget(self.Cancel)
        self.splitter = QtWidgets.QSplitter(parent=Emp_reg)
        self.splitter.setGeometry(QtCore.QRect(30, 110, 237, 249))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(parent=self.splitter)
        self.label.setObjectName("label")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.ID = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.ID.setObjectName("ID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.ID)
        self.ID_t = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.ID_t.setObjectName("ID_t")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ID_t)
        self.Name_l = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.Name_l.setObjectName("Name_l")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Name_l)
        self.Name_t = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.Name_t.setObjectName("Name_t")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Name_t)
        self.Phone_l = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.Phone_l.setObjectName("Phone_l")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Phone_l)
        self.Phone_t = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.Phone_t.setObjectName("Phone_t")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Phone_t)
        self.Job_l = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.Job_l.setObjectName("Job_l")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Job_l)
        self.Title_t = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.Title_t.setObjectName("Title_t")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Title_t)
        self.Vac_l = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.Vac_l.setObjectName("Vac_l")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Vac_l)
        self.Vac_b = QtWidgets.QSpinBox(parent=self.layoutWidget1)
        self.Vac_b.setObjectName("Vac_b")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Vac_b)
        self.Exec_l = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.Exec_l.setObjectName("Exec_l")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Exec_l)
        self.Exec_t = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.Exec_t.setObjectName("Exec_t")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Exec_t)
        self.Face_l = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.Face_l.setObjectName("Face_l")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Face_l)
        self.Face_t = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.Face_t.setObjectName("Face_t")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Face_t)
        self.pushButton = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pushButton)

        self.retranslateUi(Emp_reg)
        QtCore.QMetaObject.connectSlotsByName(Emp_reg)

    def retranslateUi(self, Emp_reg):
        _translate = QtCore.QCoreApplication.translate
        Emp_reg.setWindowTitle(_translate("Emp_reg", "Register Form"))
        self.Register.setText(_translate("Emp_reg", "Register"))
        self.Cancel.setText(_translate("Emp_reg", "Cancel"))
        self.label.setText(_translate("Emp_reg", "TextLabel"))
        self.ID.setText(_translate("Emp_reg", "ID"))
        self.Name_l.setText(_translate("Emp_reg", "Name"))
        self.Phone_l.setText(_translate("Emp_reg", "Phone Number"))
        self.Job_l.setText(_translate("Emp_reg", "Job Title"))
        self.Vac_l.setText(_translate("Emp_reg", "Vacations"))
        self.Exec_l.setText(_translate("Emp_reg", "Excuses"))
        self.Face_l.setText(_translate("Emp_reg", "Face ID"))
        self.pushButton.setText(_translate("Emp_reg", "Start Facial Recognition"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Emp_reg = QtWidgets.QWidget()
    ui = Ui_Emp_reg()
    ui.setupUi(Emp_reg)
    Emp_reg.show()
    sys.exit(app.exec())
